name: Deploy DotNet project to Azure Function App

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'tools/deploy/module2/**'
      - 'azure-function-workflow.yaml'

env:
 
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'tools/deploy/module2/TransactionClassifier'       # set this to the path to your function app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'                   # set this to the dotnet version to use (e.g. '2.1.x', '3.1.x', '5.0.x')
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'retrieve the Function App name'
      id: get_functionapp_name
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "##[set-output name=appname;]$(az functionapp list --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --query "[].name" -o tsv)"
        
    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
      # set app_name equal to output from "retrieve the Function App name" step
        app-name: ${{ steps.get_functionapp_name.outputs.appname }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples